### ISSUE TITLE
uCoin node won't start

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin_ynh#5]
I don't know why uCoin node won't start:
```bash
/home/admin/.ucoin/node/bin/node /home/admin/.ucoin/node_modules/pm2/bin/pm2 start -f /home/admin/.ucoin/bin/ucoind --name ucoin_default --interpreter=/home/admin/.ucoin/node/bin/node --node-args=--harmony --log /home/admin/.config/ucoin/ucoin_default/ucoin.log --error /home/admin/.config/ucoin/ucoin_default/ucoin.err.log --merge-logs -- start --mdb ucoin_default --httplogs
[PM2] restartProcessId process id 0
[PM2] Process successfully started
┌───────────────┬────┬──────┬─────┬─────────┬─────────┬────────┬────────┬──────────┐
│ App name      │ id │ mode │ pid │ status  │ restart │ uptime │ memory │ watching │
├───────────────┼────┼──────┼─────┼─────────┼─────────┼────────┼────────┼──────────┤
│ ucoin_default │ 0  │ fork │ N/A │ errored │ 1       │ 0      │ 0 B    │ disabled │
└───────────────┴────┴──────┴─────┴─────────┴─────────┴────────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
admin@yunohost:~$ ucoind logs
[PM2] Tailing last 20 lines for [ucoin_default] process 

ucoin_default-0 (err): path.js:435
ucoin_default-0 (err):     var path = (i >= 0) ? arguments[i] : process.cwd();
ucoin_default-0 (err):                                                  ^
ucoin_default-0 (err): Error: ENOENT, no such file or directory
ucoin_default-0 (err):     at Error (native)
ucoin_default-0 (err):     at Object.posix.resolve (path.js:435:50)
ucoin_default-0 (err):     at Function.Module._resolveLookupPaths (module.js:251:17)
ucoin_default-0 (err):     at Function.Module._resolveFilename (module.js:326:31)
ucoin_default-0 (err):     at Function.Module._load (module.js:278:25)
ucoin_default-0 (err):     at Module.require (module.js:365:17)
ucoin_default-0 (err):     at require (module.js:384:17)
ucoin_default-0 (err):     at Object.<anonymous> (/home/admin/.ucoin/bin/ucoind:15:19)
ucoin_default-0 (err):     at Module._compile (module.js:460:26)
ucoin_default-0 (err):     at Object.Module._extensions..js (module.js:478:10)
```
That's may be due to an environement variable or to a wrong path.

**Comment by M5oul** [comment]
uCoin node is starting very well installing manually with YunoHost admin user.
I didn't restart the shell, I did theses commands:
```bash
UCOIN_DIR="/home/admin/.ucoin"
[ -s "$UCOIN_DIR/ucoin.sh" ] && . "$UCOIN_DIR/ucoin.sh"
```

**Comment by M5oul** [comment]
[Logs of installation from YunoHost package](https://moul.re/zerobin/?aa7db314cac0b6f9#iSjm/Lb2TU35bdLIhlCxh+BQtjMe+nLiBwx9886J82c=).

**Comment by M5oul** [comment]
Solution found on https://github.com/foreverjs/forever/issues/200.

**Comment by M5oul** [comment]
Don't seems to be solved. After install done, this solve:
```bash
exit
ssh admin@domain.tld
ucoind delete
ucoind start
```
It seems their is an issue launching the node inside YunoHost install shell.

**Comment by scith** [comment]
Thanks for solving the other issues. I'll try to remove and reinstall the package once this is solved if you want :+1: Good job

**Comment by M5oul** [comment]
Finally, uCoin node **start** very well since [daemonize2 replaced PM2 daemon manager](https://github.com/ucoin-io/ucoin/issues/296) :smile_cat:
